#-----------------------------------------------------------------------------
# This file contains specific configuration values for testing on GitHub Actions.
#-----------------------------------------------------------------------------

test.app.frontend.url=http\://localhost\:8080
test.app.backend.url=http\://localhost\:8080
test.csrf.key=samplekey
test.backdoor.key=samplekey
test.selenium.browser=firefox
test.browser.closeonfailure=true
test.timeout=5
test.admin=app_admin@gmail.com
