#-----------------------------------------------------------------------------
# This file contains some configuration values used during E2E testing.
# It should be placed in src\e2e\resources
# Use '\' to escape ':' e.g., http\://google.com
#-----------------------------------------------------------------------------

# This is the frontend url of the app we are testing against.
# e.g. test.app.frontend.url=http\://localhost\:8080
# e.g. test.app.frontend.url=https\://8-0-0-dot-teammates-john.appspot.com
# Note: the '.' in the url has been replaced by -dot- to support https connection for the staging server.
test.app.frontend.url=http\://localhost\:8080

# This is the backend url of the app we are testing against.
# e.g. test.app.backend.url=http\://localhost\:8080
# e.g. test.app.backend.url=https\://8-0-0-dot-teammates-john.appspot.com
# Note: the '.' in the url has been replaced by -dot- to support https connection for the staging server.
test.app.backend.url=http\://localhost\:8080

# This is the key that the test suite uses to access app endpoints without origin check.
# It should match app.csrf.key in build.properties of the app being tested.
# e.g. test.csrf.key=fjdlsafdkfdk
test.csrf.key=samplekey

# This is the key that the test suite uses to access app endpoints without access control limitation.
# It should match app.backdoor.key in build.properties of the app being tested.
# e.g. test.backdoor.key=fjdlsafdkfdk
test.backdoor.key=samplekey

# These are parameters for Selenium
# allowed values for browser: firefox, chrome, edge
test.selenium.browser=firefox

# Indicates whether browser should be closed when an E2E test fails.
# Browser is always closed after an E2E test succeeds.
test.browser.closeonfailure=true

###############################################################################
# This is the timeout value, in seconds, for the waitings done in browsers
# e.g waiting for element (non-)presence/(in)visibility, for page to load
# This value can be adjusted depending on your CPU power/memory availability.
# Note that the value entered must be a positive integer.
test.timeout=5

###############################################################################
# The Google ID below should have admin permission to the system.
test.admin=app_admin@gmail.com
