package teammates.ui.webapi.endpoints;

import com.fasterxml.jackson.annotation.JsonValue;

import teammates.common.util.Const.WebPageURIs;

/**
 * API endpoints for web pages.
 */
public enum WebPageEndpoints {
    //CHECKSTYLE.OFF:JavadocVariable
    JOIN_PAGE(WebPageURIs.JOIN_PAGE),
    ADMIN_HOME_PAGE(WebPageURIs.ADMIN_HOME_PAGE),
    ADMIN_ACCOUNTS_PAGE(WebPageURIs.ADMIN_ACCOUNTS_PAGE),
    ADMIN_SEARCH_PAGE(WebPageURIs.ADMIN_SEARCH_PAGE),
    ADMIN_SESSIONS_PAGE(WebPageURIs.ADMIN_SESSIONS_PAGE),
    ADMIN_TIMEZONE_PAGE(WebPageURIs.ADMIN_TIMEZONE_PAGE),
    INSTRUCTOR_HOME_PAGE(WebPageURIs.INSTRUCTOR_HOME_PAGE),
    INSTRUCTOR_SEARCH_PAGE(WebPageURIs.INSTRUCTOR_SEARCH_PAGE),
    INSTRUCTOR_SESSIONS_PAGE(WebPageURIs.INSTRUCTOR_SESSIONS_PAGE),
    INSTRUCTOR_SESSION_SUBMISSION_PAGE(WebPageURIs.INSTRUCTOR_SESSION_SUBMISSION_PAGE),
    INSTRUCTOR_SESSION_EDIT_PAGE(WebPageURIs.INSTRUCTOR_SESSION_EDIT_PAGE),
    INSTRUCTOR_COURSES_PAGE(WebPageURIs.INSTRUCTOR_COURSES_PAGE),
    INSTRUCTOR_COURSE_DETAILS_PAGE(WebPageURIs.INSTRUCTOR_COURSE_DETAILS_PAGE),
    INSTRUCTOR_COURSE_EDIT_PAGE(WebPageURIs.INSTRUCTOR_COURSE_EDIT_PAGE),
    INSTRUCTOR_COURSE_ENROLL_PAGE(WebPageURIs.INSTRUCTOR_COURSE_ENROLL_PAGE),
    INSTRUCTOR_COURSE_STUDENT_DETAILS_PAGE(WebPageURIs.INSTRUCTOR_COURSE_STUDENT_DETAILS_PAGE),
    INSTRUCTOR_COURSE_STUDENT_DETAILS_EDIT_PAGE(WebPageURIs.INSTRUCTOR_COURSE_STUDENT_DETAILS_EDIT_PAGE),
    INSTRUCTOR_STUDENT_LIST_PAGE(WebPageURIs.INSTRUCTOR_STUDENT_LIST_PAGE),
    INSTRUCTOR_STUDENT_RECORDS_PAGE(WebPageURIs.INSTRUCTOR_STUDENT_RECORDS_PAGE),
    STUDENT_HOME_PAGE(WebPageURIs.STUDENT_HOME_PAGE),
    STUDENT_COURSE_DETAILS_PAGE(WebPageURIs.STUDENT_COURSE_DETAILS_PAGE),
    STUDENT_PROFILE_PAGE(WebPageURIs.STUDENT_PROFILE_PAGE),
    STUDENT_SESSION_RESULTS_PAGE(WebPageURIs.STUDENT_SESSION_RESULTS_PAGE),
    SESSION_RESULTS_PAGE(WebPageURIs.SESSION_RESULTS_PAGE),
    SESSION_SUBMISSION_PAGE(WebPageURIs.SESSION_SUBMISSION_PAGE),
    SESSIONS_LINK_RECOVERY_PAGE(WebPageURIs.SESSIONS_LINK_RECOVERY_PAGE),
    INSTRUCTOR_HELP_PAGE(WebPageURIs.INSTRUCTOR_HELP_PAGE);
    //CHECKSTYLE.ON:JavadocVariable

    private final String url;

    WebPageEndpoints(String s) {
        this.url = s;
    }

    @JsonValue
    public String getUrl() {
        return url;
    }
}
