/* tslint:disable */
/* eslint-disable */

export enum ApiConst {
  COURSE_ID_MAX_LENGTH = 64,
  COURSE_NAME_MAX_LENGTH = 80,
  STUDENT_NAME_MAX_LENGTH = 100,
  SECTION_NAME_MAX_LENGTH = 60,
  TEAM_NAME_MAX_LENGTH = 60,
  EMAIL_MAX_LENGTH = 254,
  FEEDBACK_SESSION_NAME_MAX_LENGTH = 64,
  NOTIFICATION_TITLE_MAX_LENGTH = 80,
  CONTRIBUTION_POINT_NOT_SUBMITTED = -999,
  CONTRIBUTION_POINT_NOT_INITIALIZED = -9999,
  CONTRIBUTION_POINT_NOT_SURE = -101,
  CONTRIBUTION_POINT_EQUAL_SHARE = 100,
  NUMERICAL_SCALE_ANSWER_NOT_SUBMITTED = -999,
  RANK_OPTIONS_ANSWER_NOT_SUBMITTED = -999,
  RANK_RECIPIENTS_ANSWER_NOT_SUBMITTED = -999,
  NO_VALUE = -2147483648,
  LOGS_RETENTION_PERIOD = 30,
  STUDENT_ACTIVITY_LOGS_RETENTION_PERIOD = 90,
  SEARCH_QUERY_SIZE_LIMIT = 50,
}

export enum ApiStringConst {
  EMAIL_REGEX = "^[\\w+-][\\w+!#$%&'*/=?^_`{}~-]*(\\.[\\w+!#$%&'*/=?^_`{}~-]+)*@([A-Za-z0-9-]+\\.)+[A-Za-z]+$",
}

export enum DefaultInstructorPermissions {
  COOWNER = "{\"canModifyCourse\":true,\"canModifyInstructor\":true,\"canModifySession\":true,\"canModifyStudent\":true,\"canViewStudentInSections\":true,\"canViewSessionInSections\":true,\"canSubmitSessionInSections\":true,\"canModifySessionCommentsInSections\":true}",
  MANAGER = "{\"canModifyCourse\":false,\"canModifyInstructor\":true,\"canModifySession\":true,\"canModifyStudent\":true,\"canViewStudentInSections\":true,\"canViewSessionInSections\":true,\"canSubmitSessionInSections\":true,\"canModifySessionCommentsInSections\":true}",
  OBSERVER = "{\"canModifyCourse\":false,\"canModifyInstructor\":false,\"canModifySession\":false,\"canModifyStudent\":false,\"canViewStudentInSections\":true,\"canViewSessionInSections\":true,\"canSubmitSessionInSections\":false,\"canModifySessionCommentsInSections\":false}",
  TUTOR = "{\"canModifyCourse\":false,\"canModifyInstructor\":false,\"canModifySession\":false,\"canModifyStudent\":false,\"canViewStudentInSections\":true,\"canViewSessionInSections\":true,\"canSubmitSessionInSections\":true,\"canModifySessionCommentsInSections\":false}",
  CUSTOM = "{\"canModifyCourse\":false,\"canModifyInstructor\":false,\"canModifySession\":false,\"canModifyStudent\":false,\"canViewStudentInSections\":false,\"canViewSessionInSections\":false,\"canSubmitSessionInSections\":false,\"canModifySessionCommentsInSections\":false}",
}

export enum QuestionTypeStructures {
  DEFAULT_CONTRIBUTION_QUESTION_DETAILS = "{\"questionType\":\"CONTRIB\",\"questionText\":\"\",\"isZeroSum\":true,\"isNotSureAllowed\":false}",
  DEFAULT_CONTRIBUTION_RESPONSE_DETAILS = "{\"questionType\":\"CONTRIB\",\"answer\":-999}",
  DEFAULT_CONSTSUM_OPTIONS_QUESTION_DETAILS = "{\"questionType\":\"CONSTSUM_OPTIONS\",\"questionText\":\"\",\"constSumOptions\":[\"\",\"\"],\"distributeToRecipients\":false,\"pointsPerOption\":false,\"forceUnevenDistribution\":false,\"distributePointsFor\":\"None\",\"points\":100}",
  DEFAULT_CONSTSUM_RECIPIENTS_QUESTION_DETAILS = "{\"questionType\":\"CONSTSUM_RECIPIENTS\",\"questionText\":\"\",\"constSumOptions\":[],\"distributeToRecipients\":true,\"pointsPerOption\":false,\"forceUnevenDistribution\":false,\"distributePointsFor\":\"None\",\"points\":100}",
  DEFAULT_CONSTSUM_RESPONSE_DETAILS = "{\"questionType\":\"CONSTSUM\",\"answers\":[]}",
  DEFAULT_MCQ_QUESTION_DETAILS = "{\"questionType\":\"MCQ\",\"questionText\":\"\",\"hasAssignedWeights\":false,\"mcqWeights\":[],\"mcqOtherWeight\":0.0,\"mcqChoices\":[],\"otherEnabled\":false,\"questionDropdownEnabled\":false,\"generateOptionsFor\":\"NONE\"}",
  DEFAULT_MCQ_RESPONSE_DETAILS = "{\"questionType\":\"MCQ\",\"answer\":\"\",\"isOther\":false,\"otherFieldContent\":\"\"}",
  DEFAULT_MSQ_QUESTION_DETAILS = "{\"questionType\":\"MSQ\",\"questionText\":\"\",\"msqChoices\":[],\"otherEnabled\":false,\"hasAssignedWeights\":false,\"msqWeights\":[],\"msqOtherWeight\":0.0,\"generateOptionsFor\":\"NONE\",\"maxSelectableChoices\":-2147483648,\"minSelectableChoices\":-2147483648}",
  DEFAULT_MSQ_RESPONSE_DETAILS = "{\"questionType\":\"MSQ\",\"answers\":[],\"isOther\":false,\"otherFieldContent\":\"\"}",
  DEFAULT_NUMSCALE_QUESTION_DETAILS = "{\"questionType\":\"NUMSCALE\",\"questionText\":\"\",\"minScale\":1,\"maxScale\":5,\"step\":0.5}",
  DEFAULT_NUMSCALE_RESPONSE_DETAILS = "{\"questionType\":\"NUMSCALE\",\"answer\":-999.0}",
  DEFAULT_RANK_OPTIONS_QUESTION_DETAILS = "{\"questionType\":\"RANK_OPTIONS\",\"questionText\":\"\",\"minOptionsToBeRanked\":-2147483648,\"maxOptionsToBeRanked\":-2147483648,\"areDuplicatesAllowed\":false,\"options\":[]}",
  DEFAULT_RANK_OPTIONS_RESPONSE_DETAILS = "{\"questionType\":\"RANK_OPTIONS\",\"answers\":[]}",
  DEFAULT_RANK_RECIPIENTS_QUESTION_DETAILS = "{\"questionType\":\"RANK_RECIPIENTS\",\"questionText\":\"\",\"minOptionsToBeRanked\":-2147483648,\"maxOptionsToBeRanked\":-2147483648,\"areDuplicatesAllowed\":false}",
  DEFAULT_RANK_RECIPIENTS_RESPONSE_DETAILS = "{\"questionType\":\"RANK_RECIPIENTS\",\"answer\":-999}",
  DEFAULT_RUBRIC_QUESTION_DETAILS = "{\"questionType\":\"RUBRIC\",\"questionText\":\"\",\"hasAssignedWeights\":false,\"rubricWeightsForEachCell\":[],\"rubricChoices\":[],\"rubricSubQuestions\":[],\"rubricDescriptions\":[]}",
  DEFAULT_RUBRIC_RESPONSE_DETAILS = "{\"questionType\":\"RUBRIC\",\"answer\":[]}",
  DEFAULT_TEXT_QUESTION_DETAILS = "{\"questionType\":\"TEXT\",\"questionText\":\"\",\"shouldAllowRichText\":true}",
  DEFAULT_TEXT_RESPONSE_DETAILS = "{\"questionType\":\"TEXT\",\"answer\":\"\"}",
}

export enum ResourceEndpoints {
  ERROR_REPORT = "/webapi/errorreport",
  AUTH = "/webapi/auth",
  AUTH_REGKEY = "/webapi/auth/regkey",
  ACCOUNT = "/webapi/account",
  ACCOUNT_RESET = "/webapi/account/reset",
  ACCOUNT_REQUEST = "/webapi/account/request",
  ACCOUNT_REQUESTS = "/webapi/account/requests",
  ACCOUNT_REQUEST_RESET = "/webapi/account/request/reset",
  ACCOUNT_REQUEST_REJECT = "/webapi/account/request/rejection",
  ACCOUNT_REQUEST_APPROVE = "/webapi/account/request/approval",
  RESPONSE_COMMENT = "/webapi/responsecomment",
  COURSE = "/webapi/course",
  BIN_COURSE = "/webapi/bin/course",
  COURSE_SECTIONS = "/webapi/course/sections",
  COURSES = "/webapi/courses",
  INSTRUCTORS = "/webapi/instructors",
  INSTRUCTOR = "/webapi/instructor",
  INSTRUCTOR_PRIVILEGE = "/webapi/instructor/privilege",
  INSTRUCTOR_KEY = "/webapi/instructor/key",
  RESULT = "/webapi/result",
  STUDENTS = "/webapi/students",
  STUDENT = "/webapi/student",
  STUDENT_KEY = "/webapi/student/key",
  SESSIONS_ONGOING = "/webapi/sessions/ongoing",
  SESSION = "/webapi/session",
  SESSION_DEADLINE_EXTENSIONS = "/webapi/session/deadlineextensions",
  SESSION_LOGS = "/webapi/logs/session",
  SESSION_PUBLISH = "/webapi/session/publish",
  SESSION_REMIND_SUBMISSION = "/webapi/session/remind/submission",
  SESSION_REMIND_RESULT = "/webapi/session/remind/result",
  SESSION_STATS = "/webapi/session/stats",
  SESSION_SUBMITTED_GIVER_SET = "/webapi/session/submitted/giverset",
  SESSIONS = "/webapi/sessions",
  BIN_SESSION = "/webapi/bin/session",
  QUESTIONS = "/webapi/questions",
  QUESTION = "/webapi/question",
  QUESTION_RECIPIENTS = "/webapi/question/recipients",
  RESPONSES = "/webapi/responses",
  HAS_RESPONSES = "/webapi/hasResponses",
  NOTIFICATION = "/webapi/notification",
  NOTIFICATIONS = "/webapi/notifications",
  NOTIFICATION_READ = "/webapi/notification/read",
  JOIN = "/webapi/join",
  JOIN_REMIND = "/webapi/join/remind",
  TIMEZONE = "/webapi/timezone",
  SESSION_LINKS_RECOVERY = "/webapi/sessionlinksrecovery",
  EMAIL = "/webapi/email",
  SEARCH_ACCOUNT_REQUESTS = "/webapi/search/accountrequests",
  SEARCH_INSTRUCTORS = "/webapi/search/instructors",
  SEARCH_STUDENTS = "/webapi/search/students",
  USAGE_STATISTICS = "/webapi/usagestats",
  ACTION_CLASS = "/webapi/actionclass",
  LOGIN_EMAIL = "/webapi/email/login",
}
