@startuml
!include diagrams/style.puml
skinparam componentBackgroundColor MODEL_COLOR_T1
skinparam componentFontColor #FFFFFF
skinparam packageBackgroundColor #FFFFFF
skinparam rectangleBackgroundColor MODEL_COLOR
skinparam rectangleFontColor #FFFFFF
skinparam arrowColor #000000

component Client {
    package client::scripts {
        folder ::scripts {
            rectangle ClientScripts
        }
    }

    package client::connector {
        rectangle DatastoreClient
    }
}

database "Google\nCloud\nDatastore" as GCD STORAGE_COLOR_T1
rectangle LogicAPI
rectangle StorageAPI

ClientScripts -> DatastoreClient
ClientScripts ..> LogicAPI
ClientScripts ..> StorageAPI
DatastoreClient ..> GCD

@enduml
