@startuml
!include diagrams/style.puml
skinparam componentBackgroundColor MODEL_COLOR_T1
skinparam componentFontColor #FFFFFF
skinparam packageBackgroundColor #FFFFFF
skinparam rectangleBackgroundColor MODEL_COLOR
skinparam rectangleFontColor #FFFFFF
skinparam arrowColor #000000

component TestDriver {
    package TestCases {
        folder "*.spec.ts" as SpecTs {
            rectangle FrontEndUnitTests
        }

        folder "::common" as Common {
            rectangle "Test cases that do not need \n simulated database" as TC1
        }

       folder "::logic, ::storage, ::ui" as LogicStorageWebAPI {
            rectangle "Test cases that need \n simulated database" as TC2
       }
    }

    package test {
        rectangle BaseTestCase
        rectangle BaseTestCaseWithDatabaseAccess
        rectangle "Mock*" as Mock
        rectangle TestProperties
        rectangle FileHelper
    }
}

file test.properties
rectangle TestNG
rectangle Jest
rectangle LocalFilesForTesting

TestNG ..> TestCases
Jest ..> FrontEndUnitTests
TC1 -> BaseTestCase
TC2 -> BaseTestCaseWithDatabaseAccess
BaseTestCaseWithDatabaseAccess -> BaseTestCase
FileHelper ..> LocalFilesForTesting
TestProperties ..> test.properties

' The hidden associations are for positioning purposes only
TestCases -[hidden]down- test
BaseTestCaseWithDatabaseAccess -[hidden]down- Mock
BaseTestCaseWithDatabaseAccess -[hidden]down- TestProperties
BaseTestCase -[hidden]down- FileHelper


@enduml
