// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/appengine/logging/v1/request_log.proto

package com.google.appengine.logging.v1;

public interface LogLineOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.appengine.logging.v1.LogLine)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Approximate time when this log entry was made.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp time = 1;</code>
   */
  boolean hasTime();
  /**
   * <pre>
   * Approximate time when this log entry was made.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp time = 1;</code>
   */
  com.google.protobuf.Timestamp getTime();
  /**
   * <pre>
   * Approximate time when this log entry was made.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp time = 1;</code>
   */
  com.google.protobuf.TimestampOrBuilder getTimeOrBuilder();

  /**
   * <pre>
   * Severity of this log entry.
   * </pre>
   *
   * <code>.google.logging.type.LogSeverity severity = 2;</code>
   */
  int getSeverityValue();
  /**
   * <pre>
   * Severity of this log entry.
   * </pre>
   *
   * <code>.google.logging.type.LogSeverity severity = 2;</code>
   */
  com.google.logging.type.LogSeverity getSeverity();

  /**
   * <pre>
   * App-provided log message.
   * </pre>
   *
   * <code>string log_message = 3;</code>
   */
  java.lang.String getLogMessage();
  /**
   * <pre>
   * App-provided log message.
   * </pre>
   *
   * <code>string log_message = 3;</code>
   */
  com.google.protobuf.ByteString
      getLogMessageBytes();

  /**
   * <pre>
   * Where in the source code this log message was written.
   * </pre>
   *
   * <code>.google.appengine.logging.v1.SourceLocation source_location = 4;</code>
   */
  boolean hasSourceLocation();
  /**
   * <pre>
   * Where in the source code this log message was written.
   * </pre>
   *
   * <code>.google.appengine.logging.v1.SourceLocation source_location = 4;</code>
   */
  com.google.appengine.logging.v1.SourceLocation getSourceLocation();
  /**
   * <pre>
   * Where in the source code this log message was written.
   * </pre>
   *
   * <code>.google.appengine.logging.v1.SourceLocation source_location = 4;</code>
   */
  com.google.appengine.logging.v1.SourceLocationOrBuilder getSourceLocationOrBuilder();
}
