// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/appengine/logging/v1/request_log.proto

package com.google.appengine.logging.v1;

public interface SourceReferenceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.appengine.logging.v1.SourceReference)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Optional. A URI string identifying the repository.
   * Example: "https://github.com/GoogleCloudPlatform/kubernetes.git"
   * </pre>
   *
   * <code>string repository = 1;</code>
   */
  java.lang.String getRepository();
  /**
   * <pre>
   * Optional. A URI string identifying the repository.
   * Example: "https://github.com/GoogleCloudPlatform/kubernetes.git"
   * </pre>
   *
   * <code>string repository = 1;</code>
   */
  com.google.protobuf.ByteString
      getRepositoryBytes();

  /**
   * <pre>
   * The canonical and persistent identifier of the deployed revision.
   * Example (git): "0035781c50ec7aa23385dc841529ce8a4b70db1b"
   * </pre>
   *
   * <code>string revision_id = 2;</code>
   */
  java.lang.String getRevisionId();
  /**
   * <pre>
   * The canonical and persistent identifier of the deployed revision.
   * Example (git): "0035781c50ec7aa23385dc841529ce8a4b70db1b"
   * </pre>
   *
   * <code>string revision_id = 2;</code>
   */
  com.google.protobuf.ByteString
      getRevisionIdBytes();
}
