// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/appengine/logging/v1/request_log.proto

package com.google.appengine.logging.v1;

public interface SourceLocationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.appengine.logging.v1.SourceLocation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Source file name. Depending on the runtime environment, this might be a
   * simple name or a fully-qualified name.
   * </pre>
   *
   * <code>string file = 1;</code>
   */
  java.lang.String getFile();
  /**
   * <pre>
   * Source file name. Depending on the runtime environment, this might be a
   * simple name or a fully-qualified name.
   * </pre>
   *
   * <code>string file = 1;</code>
   */
  com.google.protobuf.ByteString
      getFileBytes();

  /**
   * <pre>
   * Line within the source file.
   * </pre>
   *
   * <code>int64 line = 2;</code>
   */
  long getLine();

  /**
   * <pre>
   * Human-readable name of the function or method being invoked, with optional
   * context such as the class or package name. This information is used in
   * contexts such as the logs viewer, where a file and line number are less
   * meaningful. The format can vary by language. For example:
   * `qual.if.ied.Class.method` (Java), `dir/package.func` (Go), `function`
   * (Python).
   * </pre>
   *
   * <code>string function_name = 3;</code>
   */
  java.lang.String getFunctionName();
  /**
   * <pre>
   * Human-readable name of the function or method being invoked, with optional
   * context such as the class or package name. This information is used in
   * contexts such as the logs viewer, where a file and line number are less
   * meaningful. The format can vary by language. For example:
   * `qual.if.ied.Class.method` (Java), `dir/package.func` (Go), `function`
   * (Python).
   * </pre>
   *
   * <code>string function_name = 3;</code>
   */
  com.google.protobuf.ByteString
      getFunctionNameBytes();
}
