package teammates.ui.constants;

import com.fasterxml.jackson.annotation.JsonValue;

import teammates.common.util.Const.Actions;

/**
 * Action names for http requests.
 */
public enum ActionNames {
    //CHECKSTYLE.OFF:JavadocVariable
    PUT_DATA_BUNDLE_ACTION(Actions.PUT_DATA_BUNDLE_ACTION),
    DELETE_DATA_BUNDLE_ACTION(Actions.DELETE_DATA_BUNDLE_ACTION),
    PUT_DATA_BUNDLE_DOCUMENTS_ACTION(Actions.PUT_DATA_BUNDLE_DOCUMENTS_ACTION),
    ADMIN_EXCEPTION_TEST_ACTION(Actions.ADMIN_EXCEPTION_TEST_ACTION),
    SEND_ERROR_REPORT_ACTION(Actions.SEND_ERROR_REPORT_ACTION),
    GET_TIME_ZONES_ACTION(Actions.GET_TIME_ZONES_ACTION),
    GET_NATIONALITIES_ACTION(Actions.GET_NATIONALITIES_ACTION),
    GET_AUTH_INFO_ACTION(Actions.GET_AUTH_INFO_ACTION),
    GET_REGKEY_VALIDITY_ACTION(Actions.GET_REGKEY_VALIDITY_ACTION),
    GET_ACCOUNT_ACTION(Actions.GET_ACCOUNT_ACTION),
    CREATE_ACCOUNT_ACTION(Actions.CREATE_ACCOUNT_ACTION),
    DELETE_ACCOUNT_ACTION(Actions.DELETE_ACCOUNT_ACTION),
    DOWNGRADE_ACCOUNT_ACTION(Actions.DOWNGRADE_ACCOUNT_ACTION),
    RESET_ACCOUNT_ACTION(Actions.RESET_ACCOUNT_ACTION),
    GET_COURSE_ACTION(Actions.GET_COURSE_ACTION),
    DELETE_COURSE_ACTION(Actions.DELETE_COURSE_ACTION),
    CREATE_COURSE_ACTION(Actions.CREATE_COURSE_ACTION),
    UPDATE_COURSE_ACTION(Actions.UPDATE_COURSE_ACTION),
    ARCHIVE_COURSE_ACTION(Actions.ARCHIVE_COURSE_ACTION),
    BIN_COURSE_ACTION(Actions.BIN_COURSE_ACTION),
    RESTORE_COURSE_ACTION(Actions.RESTORE_COURSE_ACTION),
    GET_COURSES_ACTION(Actions.GET_COURSES_ACTION),
    GET_COURSE_SECTION_NAMES_ACTION(Actions.GET_COURSE_SECTION_NAMES_ACTION),
    GET_INSTRUCTORS_ACTION(Actions.GET_INSTRUCTORS_ACTION),
    GET_INSTRUCTOR_ACTION(Actions.GET_INSTRUCTOR_ACTION),
    DELETE_INSTRUCTOR_ACTION(Actions.DELETE_INSTRUCTOR_ACTION),
    GET_INSTRUCTOR_PRIVILEGE_ACTION(Actions.GET_INSTRUCTOR_PRIVILEGE_ACTION),
    UPDATE_INSTRUCTOR_PRIVILEGE_ACTION(Actions.UPDATE_INSTRUCTOR_PRIVILEGE_ACTION),
    CREATE_FEEDBACK_RESPONSE_COMMENT_ACTION(Actions.CREATE_FEEDBACK_RESPONSE_COMMENT_ACTION),
    GET_FEEDBACK_RESPONSE_COMMENT_ACTION(Actions.GET_FEEDBACK_RESPONSE_COMMENT_ACTION),
    UPDATE_FEEDBACK_RESPONSE_COMMENT_ACTION(Actions.UPDATE_FEEDBACK_RESPONSE_COMMENT_ACTION),
    DELETE_FEEDBACK_RESPONSE_COMMENT_ACTION(Actions.DELETE_FEEDBACK_RESPONSE_COMMENT_ACTION),
    GET_SESSION_RESULTS_ACTION(Actions.GET_SESSION_RESULTS_ACTION),
    GET_STUDENTS_ACTION(Actions.GET_STUDENTS_ACTION),
    ENROLL_STUDENTS_ACTION(Actions.ENROLL_STUDENTS_ACTION),
    DELETE_STUDENTS_ACTION(Actions.DELETE_STUDENTS_ACTION),
    DELETE_STUDENT_ACTION(Actions.DELETE_STUDENT_ACTION),
    GET_STUDENT_ACTION(Actions.GET_STUDENT_ACTION),
    UPDATE_STUDENT_ACTION(Actions.UPDATE_STUDENT_ACTION),
    SEARCH_INSTRUCTORS_ACTION(Actions.SEARCH_INSTRUCTORS_ACTION),
    SEARCH_STUDENTS_ACTION(Actions.SEARCH_STUDENTS_ACTION),
    GENERATE_EMAIL_ACTION(Actions.GENERATE_EMAIL_ACTION),
    GET_ONGOING_SESSIONS_ACTION(Actions.GET_ONGOING_SESSIONS_ACTION),
    GET_SESSION_RESPONSE_STATS_ACTION(Actions.GET_SESSION_RESPONSE_STATS_ACTION),
    GET_FEEDBACK_SESSION_ACTION(Actions.GET_FEEDBACK_SESSION_ACTION),
    UPDATE_FEEDBACK_SESSION_ACTION(Actions.UPDATE_FEEDBACK_SESSION_ACTION),
    CREATE_FEEDBACK_SESSION_ACTION(Actions.CREATE_FEEDBACK_SESSION_ACTION),
    DELETE_FEEDBACK_SESSION_ACTION(Actions.DELETE_FEEDBACK_SESSION_ACTION),
    PUBLISH_FEEDBACK_SESSION_ACTION(Actions.PUBLISH_FEEDBACK_SESSION_ACTION),
    UNPUBLISH_FEEDBACK_SESSION_ACTION(Actions.UNPUBLISH_FEEDBACK_SESSION_ACTION),
    GET_FEEDBACK_SESSION_SUBMITTED_GIVER_SET_ACTION(Actions.GET_FEEDBACK_SESSION_SUBMITTED_GIVER_SET_ACTION),
    REMIND_FEEDBACK_SESSION_SUBMISSION_ACTION(Actions.REMIND_FEEDBACK_SESSION_SUBMISSION_ACTION),
    REMIND_FEEDBACK_SESSION_RESULT_ACTION(Actions.REMIND_FEEDBACK_SESSION_RESULT_ACTION),
    GET_FEEDBACK_SESSIONS_ACTION(Actions.GET_FEEDBACK_SESSIONS_ACTION),
    BIN_FEEDBACK_SESSION_ACTION(Actions.BIN_FEEDBACK_SESSION_ACTION),
    RESTORE_FEEDBACK_SESSION_ACTION(Actions.RESTORE_FEEDBACK_SESSION_ACTION),
    REGENERATE_STUDENT_COURSE_LINKS_ACTION(Actions.REGENERATE_STUDENT_COURSE_LINKS_ACTION),
    GET_FEEDBACK_QUESTIONS_ACTION(Actions.GET_FEEDBACK_QUESTIONS_ACTION),
    CREATE_FEEDBACK_QUESTION_ACTION(Actions.CREATE_FEEDBACK_QUESTION_ACTION),
    UPDATE_FEEDBACK_QUESTION_ACTION(Actions.UPDATE_FEEDBACK_QUESTION_ACTION),
    DELETE_FEEDBACK_QUESTION_ACTION(Actions.DELETE_FEEDBACK_QUESTION_ACTION),
    GET_FEEDBACK_QUESTION_RECIPIENTS_ACTION(Actions.GET_FEEDBACK_QUESTION_RECIPIENTS_ACTION),
    GET_FEEDBACK_RESPONSES_ACTION(Actions.GET_FEEDBACK_RESPONSES_ACTION),
    SUBMIT_FEEDBACK_RESPONSES_ACTION(Actions.SUBMIT_FEEDBACK_RESPONSES_ACTION),
    GET_HAS_RESPONSES_ACTION(Actions.GET_HAS_RESPONSES_ACTION),
    GET_LOCAL_DATE_TIME_INFO_ACTION(Actions.GET_LOCAL_DATE_TIME_INFO_ACTION),
    SESSION_LINKS_RECOVERY_ACTION(Actions.SESSION_LINKS_RECOVERY_ACTION),
    GET_COURSE_JOIN_STATUS_ACTION(Actions.GET_COURSE_JOIN_STATUS_ACTION),
    JOIN_COURSE_ACTION(Actions.JOIN_COURSE_ACTION),
    SEND_JOIN_REMINDER_EMAIL_ACTION(Actions.SEND_JOIN_REMINDER_EMAIL_ACTION),
    GET_STUDENT_PROFILE_ACTION(Actions.GET_STUDENT_PROFILE_ACTION),
    UPDATE_STUDENT_PROFILE_ACTION(Actions.UPDATE_STUDENT_PROFILE_ACTION),
    GET_STUDENT_PROFILE_PICTURE_ACTION(Actions.GET_STUDENT_PROFILE_PICTURE_ACTION),
    POST_STUDENT_PROFILE_PICTURE_ACTION(Actions.POST_STUDENT_PROFILE_PICTURE_ACTION),
    DELETE_STUDENT_PROFILE_PICTURE_ACTION(Actions.DELETE_STUDENT_PROFILE_PICTURE_ACTION),
    UPDATE_INSTRUCTOR_ACTION(Actions.UPDATE_INSTRUCTOR_ACTION),
    CREATE_INSTRUCTOR_ACTION(Actions.CREATE_INSTRUCTOR_ACTION),
    CREATE_FEEDBACK_SESSION_LOG_ACTION(Actions.CREATE_FEEDBACK_SESSION_LOG_ACTION),
    GET_FEEDBACK_SESSION_LOGS_ACTION(Actions.GET_FEEDBACK_SESSION_LOGS_ACTION),
    QUERY_LOGS_ACTION(Actions.QUERY_LOGS_ACTION),
    COMPILE_LOGS_ACTION(Actions.COMPILE_LOGS_ACTION),
    DATASTORE_BACKUP_ACTION(Actions.DATASTORE_BACKUP_ACTION),
    FEEDBACK_SESSION_OPENING_REMINDERS_ACTION(Actions.FEEDBACK_SESSION_OPENING_REMINDERS_ACTION),
    FEEDBACK_SESSION_CLOSED_REMINDERS_ACTION(Actions.FEEDBACK_SESSION_CLOSED_REMINDERS_ACTION),
    FEEDBACK_SESSION_CLOSING_REMINDERS_ACTION(Actions.FEEDBACK_SESSION_CLOSING_REMINDERS_ACTION),
    FEEDBACK_SESSION_PUBLISHED_REMINDERS_ACTION(Actions.FEEDBACK_SESSION_PUBLISHED_REMINDERS_ACTION),
    FEEDBACK_SESSION_PUBLISHED_EMAIL_WORKER_ACTION(Actions.FEEDBACK_SESSION_PUBLISHED_EMAIL_WORKER_ACTION),
    FEEDBACK_SESSION_RESEND_PUBLISHED_EMAIL_WORKER_ACTION(Actions.FEEDBACK_SESSION_RESEND_PUBLISHED_EMAIL_WORKER_ACTION),
    FEEDBACK_SESSION_REMIND_PARTICULAR_USERS_EMAIL_WORKER_ACTION(
            Actions.FEEDBACK_SESSION_REMIND_PARTICULAR_USERS_EMAIL_WORKER_ACTION),
    FEEDBACK_SESSION_UNPUBLISHED_EMAIL_WORKER_ACTION(Actions.FEEDBACK_SESSION_UNPUBLISHED_EMAIL_WORKER_ACTION),
    INSTRUCTOR_COURSE_JOIN_EMAIL_WORKER_ACTION(Actions.INSTRUCTOR_COURSE_JOIN_EMAIL_WORKER_ACTION),
    SEND_EMAIL_WORKER_ACTION(Actions.SEND_EMAIL_WORKER_ACTION),
    STUDENT_COURSE_JOIN_EMAIL_WORKER_ACTION(Actions.STUDENT_COURSE_JOIN_EMAIL_WORKER_ACTION);
    //CHECKSTYLE.ON:JavadocVariable

    private final String actionName;

    ActionNames(String s) {
        this.actionName = s;
    }

    @JsonValue
    public String getUrl() {
        return actionName;
    }
}
