package teammates.ui.constants;

import com.fasterxml.jackson.annotation.JsonValue;

import teammates.common.util.Const.ResourceURIs;

/**
 * API endpoints for resources.
 */
public enum ResourceEndpoints {
    //CHECKSTYLE.OFF:JavadocVariable
    ERROR_REPORT(ResourceURIs.ERROR_REPORT),
    AUTH(ResourceURIs.AUTH),
    AUTH_REGKEY(ResourceURIs.AUTH_REGKEY),
    ACCOUNT(ResourceURIs.ACCOUNT),
    ACCOUNT_LINK(ResourceURIs.ACCOUNT_LINK),
    ACCOUNT_UNLINK(ResourceURIs.ACCOUNT_UNLINK),
    ACCOUNT_VERIFICATION_REQUEST(ResourceURIs.ACCOUNT_VERIFICATION_REQUEST),
    ACCOUNT_VERIFICATION_REQUESTS(ResourceURIs.ACCOUNT_VERIFICATION_REQUESTS),
    ACCOUNT_VERIFICATION_REQUEST_REJECT(ResourceURIs.ACCOUNT_VERIFICATION_REQUEST_REJECTION),
    ACCOUNT_VERIFICATION_REQUEST_APPROVE(ResourceURIs.ACCOUNT_VERIFICATION_REQUEST_APPROVAL),
    RESPONSE_COMMENT(ResourceURIs.RESPONSE_COMMENT),
    RESPONSE_GIVER_COMMENT(ResourceURIs.RESPONSE_GIVER_COMMENT),
    COURSE(ResourceURIs.COURSE),
    BIN_COURSE(ResourceURIs.BIN_COURSE),
    COURSE_SECTIONS(ResourceURIs.COURSE_SECTIONS),
    INSTRUCTOR_COURSES(ResourceURIs.INSTRUCTOR_COURSES),
    STUDENT_COURSES(ResourceURIs.STUDENT_COURSES),
    DEMO_COURSE(ResourceURIs.DEMO_COURSE),
    INSTITUTES(ResourceURIs.INSTITUTES),
    INSTRUCTORS(ResourceURIs.INSTRUCTORS),
    INSTRUCTORS_DISPLAYED(ResourceURIs.INSTRUCTORS_DISPLAYED),
    INSTRUCTOR(ResourceURIs.INSTRUCTOR),
    OWN_INSTRUCTOR(ResourceURIs.OWN_INSTRUCTOR),
    INSTRUCTOR_PRIVILEGE(ResourceURIs.INSTRUCTOR_PRIVILEGE),
    COURSE_SESSION_RESULTS(ResourceURIs.COURSE_SESSION_RESULTS),
    USER_SESSION_RESULTS(ResourceURIs.USER_SESSION_RESULTS),
    STUDENTS(ResourceURIs.STUDENTS),
    STUDENT(ResourceURIs.STUDENT),
    OWN_STUDENT(ResourceURIs.OWN_STUDENT),
    OWN_TEAM_STUDENTS(ResourceURIs.OWN_TEAM_STUDENTS),
    USER_KEY(ResourceURIs.USER_KEY),
    SESSIONS_ONGOING(ResourceURIs.SESSIONS_ONGOING),
    SESSION(ResourceURIs.SESSION),
    SESSION_DEADLINE_EXTENSION(ResourceURIs.SESSION_DEADLINE_EXTENSION),
    SESSION_DEADLINE_EXTENSIONS(ResourceURIs.SESSION_DEADLINE_EXTENSIONS),
    SESSION_KEY_ACCESS(ResourceURIs.SESSION_KEY_ACCESS),
    SESSION_LINKS(ResourceURIs.SESSION_LINKS),
    SESSION_LOGS(ResourceURIs.SESSION_LOGS),
    SESSION_PUBLISH(ResourceURIs.SESSION_PUBLISH),
    SESSION_REMIND_SUBMISSION(ResourceURIs.SESSION_REMIND_SUBMISSION),
    SESSION_REMIND_RESULT(ResourceURIs.SESSION_REMIND_RESULT),
    SESSION_STATS(ResourceURIs.SESSION_STATS),
    SESSION_SUBMISSION(ResourceURIs.SESSION_SUBMISSION),
    SESSION_SUBMITTED_GIVER_SET(ResourceURIs.SESSION_SUBMITTED_GIVER_SET),
    SESSIONS(ResourceURIs.SESSIONS),
    BIN_SESSION(ResourceURIs.BIN_SESSION),
    QUESTIONS(ResourceURIs.QUESTIONS),
    QUESTION(ResourceURIs.QUESTION),
    RESPONSES(ResourceURIs.RESPONSES),
    HAS_RESPONSES(ResourceURIs.HAS_RESPONSES),
    NOTIFICATION(ResourceURIs.NOTIFICATION),
    NOTIFICATIONS(ResourceURIs.NOTIFICATIONS),
    NOTIFICATION_READ(ResourceURIs.NOTIFICATION_READ),
    JOIN(ResourceURIs.JOIN),
    JOIN_REMIND(ResourceURIs.JOIN_REMIND),
    TIMEZONE(ResourceURIs.TIMEZONE),
    SESSION_LINKS_RECOVERY(ResourceURIs.SESSION_LINKS_RECOVERY),
    USAGE_STATISTICS(ResourceURIs.USAGE_STATISTICS),
    CONFIG(ResourceURIs.CONFIG);
    //CHECKSTYLE.ON:JavadocVariable

    private final String url;

    ResourceEndpoints(String s) {
        this.url = s;
    }

    @JsonValue
    public String getUrl() {
        return url;
    }
}
