package teammates.storage.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import com.google.appengine.api.datastore.Text;

import com.googlecode.objectify.annotation.Entity;
import com.googlecode.objectify.annotation.Id;
import com.googlecode.objectify.annotation.Index;

import teammates.common.datatransfer.CommentParticipantType;
import teammates.common.datatransfer.CommentSendingState;
import teammates.common.datatransfer.CommentStatus;
import teammates.common.util.SanitizationHelper;

/**
 * An association class that represents the association Giver
 * --> [comments about] --> Receiver.
 * Both giver and receiver must be in the same course.
 * Currently giver is restricted only to Instructor, and
 * receiver is restricted to Student.
 */
@Entity
@Index
public class Comment extends BaseEntity {

    @Id
    private transient Long commentId;

    /** The foreign key to locate the Course object. */
    private String courseId;

    /** The giver's email used for this comment. */
    private String giverEmail;

    /** The recipient type for this comment. */
    private CommentParticipantType recipientType;

    /** The recipients' id used for this comment. E.g.
     * if the recipient type is PERSON, then it stands for
     * recipients' email; if it's TEAM, it stands for the
     * team id; if it's COURSE, it will store the course
     * id. */
    private Set<String> recipients = new HashSet<String>();

    /** The comment's status. */
    private CommentStatus status;

    /** Is this comment pending to be sent to recipient (through email) or sending or sent. */
    private CommentSendingState sendingState;

    /** Visibility options. **/
    private List<CommentParticipantType> showCommentTo = new ArrayList<CommentParticipantType>();

    private List<CommentParticipantType> showGiverNameTo = new ArrayList<CommentParticipantType>();

    private List<CommentParticipantType> showRecipientNameTo = new ArrayList<CommentParticipantType>();

    //TODO: remove this property after data migration
    /** The receiver's email used for this comment. */
    private String receiverEmail;

    /** The creation time of this comment. */
    private Date createdAt;

    /** The comment from giver for receiver. */
    private Text commentText;

    /** The e-mail of the account that last edited the comment. */
    private String lastEditorEmail;

    /** The time in which the comment is last edited. */
    private Date lastEditedAt;

    @SuppressWarnings("unused") // required by Objectify
    private Comment() {
    }

    public Comment(String courseId, String giverEmail, CommentParticipantType recipientType,
                   Set<String> recipients, CommentStatus status, CommentSendingState sendingState,
                   List<CommentParticipantType> showCommentTo, List<CommentParticipantType> showGiverNameTo,
                   List<CommentParticipantType> showRecipientNameTo, Text comment, Date date,
                   String lastEditorEmail, Date lastEditedAt) {
        this.commentId = null; //Auto generated by GAE
        this.courseId = courseId;
        this.giverEmail = giverEmail;
        this.recipientType = recipientType;
        this.recipients = recipients == null ? new HashSet<String>() : recipients;
        this.status = status;
        this.sendingState = sendingState;
        this.showCommentTo = showCommentTo == null ? new ArrayList<CommentParticipantType>() : showCommentTo;
        this.showGiverNameTo = showGiverNameTo == null ? new ArrayList<CommentParticipantType>() : showGiverNameTo;
        this.showRecipientNameTo =
                showRecipientNameTo == null ? new ArrayList<CommentParticipantType>() : showRecipientNameTo;
        this.createdAt = date;
        this.commentText = SanitizationHelper.sanitizeForRichText(comment);
        this.lastEditorEmail = lastEditorEmail == null ? giverEmail : lastEditorEmail;
        this.lastEditedAt = lastEditedAt == null ? date : lastEditedAt;
    }

    public Long getId() {
        return commentId;
    }

    /* Auto generated. Don't set this.
    public void setId(Long id) {
        this.id = id;
    }*/

    public String getCourseId() {
        return courseId;
    }

    public void setCourseId(String courseId) {
        this.courseId = courseId;
    }

    public String getGiverEmail() {
        return giverEmail;
    }

    public void setGiverEmail(String giverEmail) {
        this.giverEmail = giverEmail;
    }

    public CommentParticipantType getRecipientType() {
        return recipientType;
    }

    public void setRecipientType(CommentParticipantType recipientType) {
        this.recipientType = recipientType;
    }

    public Set<String> getRecipients() {
        return recipients;
    }

    public void setRecipients(Set<String> recipients) {
        this.recipients = recipients;
    }

    public CommentStatus getStatus() {
        return status;
    }

    public void setStatus(CommentStatus status) {
        this.status = status;
    }

    public CommentSendingState getSendingState() {
        return sendingState;
    }

    public void setSendingState(CommentSendingState sendingState) {
        this.sendingState = sendingState;
    }

    public List<CommentParticipantType> getShowCommentTo() {
        return showCommentTo;
    }

    public void setShowCommentTo(List<CommentParticipantType> showCommentTo) {
        this.showCommentTo = showCommentTo;
    }

    public List<CommentParticipantType> getShowGiverNameTo() {
        return showGiverNameTo;
    }

    public void setShowGiverNameTo(List<CommentParticipantType> showGiverNameTo) {
        this.showGiverNameTo = showGiverNameTo;
    }

    public List<CommentParticipantType> getShowRecipientNameTo() {
        return showRecipientNameTo;
    }

    public void setShowRecipientNameTo(List<CommentParticipantType> showRecipientNameTo) {
        this.showRecipientNameTo = showRecipientNameTo;
    }

    @Deprecated
    public String getReceiverEmail() {
        return receiverEmail;
    }

    @Deprecated
    public void setReceiverEmail(String receiverEmail) {
        this.receiverEmail = receiverEmail;
    }

    public Date getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    public Text getCommentText() {
        return commentText;
    }

    public void setCommentText(Text commentText) {
        this.commentText = commentText;
    }

    public void setLastEditorEmail(String lastEditorEmail) {
        this.lastEditorEmail = lastEditorEmail;
    }

    public String getLastEditorEmail() {
        return this.lastEditorEmail;
    }

    public Date getLastEditedAt() {
        return this.lastEditedAt;
    }

    public void setLastEditedAt(Date lastEditedAt) {
        this.lastEditedAt = lastEditedAt;
    }

}
