var userData = [
['Aarhus University, Denmark'],
['Abu Dhabi University, UAE'],
['Academy of Our Lady of Mercy, USA'],
['Adam Mickiewicz University, Poland'],
['Adnoc School, UAE'],
['AEDB, Brazil'],
['AEDB, Brazil'],
['Algonquin College, Canada'],
['All India Institute of Medical Sciences, Jodhpur, India'],
['Allen University, USA'],
['Amargosa Creek Middle School, USA'],
['Amsterdam University College, Netherlands'],
['Amsterdam University of Applied Sciences, Netherlands'],
['Andrew Jackson High School'],
['Anne Arundel Community College, USA'],
['AP University College Antwerp, Belgium'],
['Arcadia University, USA'],
['Arizona State University, USA'],
['Arxo, Italy'],
['Ashton Elementary, USA'],
['Asian Institute of Management, Philippines'],
['Associação Educacional Dom Bosco, Brazil'],
['Ateneo de Manila University, Philippines'],
['Ateneo School of Medicine & Public Health, Philippines'],
['Ateneo School of Medicine &amp; Public Health, Philippines'],
['Aussie Pet Mobile Groomer Training, Canada'],
['Austin Community College, USA'],
['Australian National University, Australia'],
['Bahrain Polytechnic, Bahrain'],
['Bainbridge State College, USA'],
['Ball State University, USA'],
['Bandung Institute of Technology, Indonesia'],
['Batangas State University, Philippines'],
['Bay State College, USA'],
['Baylor University, USA'],
['BCIT, Canada'],
['Bedok Green Secondary, Singapore'],
['Benedictine College, USA'],
['Benjamin Bosse High School, USA'],
['Benjamin Stoddert Middle School, USA'],
['Bessemer City High School, USA'],
['Bethany High School, USA'],
['BITS Pilani, Goa Campus, India'],
['Black Hawk College, USA'],
['Bluffton High School, USA'],
['BMZA Portland Community College, USA'],
['Bogazici University, Turkey'],
['Boise State University, USA'],
['Bond University, Australia'],
['Boston University School of Public Health, USA'],
['Bowie Junior High, USA'],
['Bowling Green State University, USA'],
['Brackweder Realschule, Germany'],
['Bradley University, USA'],
['Brigham Young University, USA'],
['Bristol-Myers Squibb, USA'],
['British Columbia Institute of Technology, Canada'],
['Brock University, Canada'],
['Brooklyn College of CUNY, USA'],
['Broward College, USA'],
['Bullock Creek High School, USA'],
['Burgerschool, Belgium'],
['Business School Lausanne, Switzerland'],
['Busleyden Atheneum, Belgium'],
['Cal Poly Pomona, USA'],
['California Baptist University, USA'],
['California State University - Long Beach, USA'],
['California State University Long Beach, USA'],
['California State University Northridge, USA'],
['California State University San Marcos, USA'],
['California State University, Long Beach, USA'],
['California State University, Northridge, USA'],
['California State University, USA'],
['Capilano University, Canada'],
['Cardiff University, UK'],
['Carnegie Mellon Tepper School, USA'],
['Carnegie Mellon University, Qatar'],
['Carnegie Mellon University, USA'],
['Carthage College, USA'],
['Catawba Valley Community College, USA'],
['Cedar Valley Christian School, USA'],
['Central Academy of Technology and Arts, USA'],
['Central High School, USA'],
['Central Louisiana Technical Community College, USA'],
['Centro Didáctico, Spain'],
['Centro Federal de Educa?o Tecnol?ica Celso Suckow da Fonseca'],
['Charlotte School of Law, USA'],
['Charotar University of Science &amp; Technology, India'],
['Ching Cheng High School, Taiwan'],
['Christ the King School, Texas, USA'],
['Chulalongkorn University, Thailand'],
['City College, Greece'],
['Clark University, USA'],
['Clarkson University, USA'],
['Clemson University, USA'],
['Clio Area High School, USA'],
['Coastal Carolina University, USA'],
['Colegio Americano del Sur, Guatemala'],
['College of William'],
['College of William and Mary, USA'],
['Collin College, USA'],
['Colorado Mountain College, USA'],
['Colorado State University, USA'],
['Columbia University, USA'],
['com437spring2014@gmail.com'],
['Concordia University, Canada'],
['Conestoga College, Canada'],
['Connally High School, USA'],
['Cork Institute of Technology, Ireland'],
['Cornell University, USA'],
['Cranfield University, UK'],
['Creighton University, USA'],
['Cumberland Valley High School, USA'],
['Curtin University, Australia'],
['Cuyahoga Community College, USA'],
['Cuyamaca College, USA'],
['Cypress College, USA'],
['Cypress Heights Academy, USA'],
['D&#39;Youville College, USA'],
['Dalton State College, USA'],
['Dartmouth College, USA'],
['De La Salle University, Philippines'],
['De la Salle University, Philippines'],
['Deakin University, Australia'],
['Deep Dive Coders'],
['Deltacredit, Russia'],
['Des Moines University, USA'],
['Dong Nai University, Vietnam'],
['Dorset College Dublin, Ireland'],
['Downstate Medical Center, Germany'],
['Drake Law School, USA'],
['Drexel University'],
['Drexel University, USA'],
['Dubiski High School, USA'],
['Dublin Institute of Technology, Ireland'],
['Dudley High School, USA'],
['Duke University, USA'],
['Dundalk Institute of Technology, Ireland'],
['Earlham College, USA'],
['East Carolina University, USA'],
['East Middle School, USA'],
['East Sac County Community School, USA'],
['Eastern High School, USA'],
['Eastern International University, Vietnam'],
['Ecole Cardinal Leger School, Canada'],
['ECPI University, USA'],
['Edgemont School, Canada'],
['EDHEC Business School, France'],
['EDHEC, France'],
['Edinburgh Napier School of Eng. and the Built Env., Scotland'],
['Edinburgh Napier University, UK'],
['Edith Cowan University, Australia'],
['EDUCSA, Canada'],
['Eindhoven University of Technology, Netherlands'],
['EKindling, Philippines'],
['Embry-Riddle Aeronautical University, Singapore'],
['Embry-Riddle Aeronautical University, USA'],
['Emil\'s Lawns, USA'],
['EMLYON Business School, France'],
['EMLyon, France'],
['Emma Lazarus High School, USA'],
['Emmanuel College, Theology and Religious Studies, UK'],
['Emmanuel College, USA'],
['Emory University, USA'],
['Energized.Org, Netherland'],
['Engineering and Science University Magnet School, USA'],
['Enlitic, USA'],
['EPFL, Switzerland'],
['EPHEC, Belgium'],
['Erasmus School of Economics, Netherlands'],
['Erasmus Student Network, Belgium'],
['Erasmus University Rotterdam, Netherlands'],
['ESC-Dijon, France'],
['Escuela Bancaria y Comercial, Mexico'],
['Escuela Superior Politecnica Del Litoral, Ecuador'],
['ETE FMC, Brazil'],
['Everett Meredith Middle School, USA'],
['Experimental Systems and Technologies Lab, Singapore'],
['Faculdade do Hospital Albert Einstein, Brazil'],
['Fairmont State University, USA'],
['Fanshawe College, Canada'],
['Fayetteville State University, USA'],
['Federal University of Minas Gerais, Brazil'],
['Firepole Marketing, Canada'],
['Florida A&amp;M University, USA'],
['Florida A&M University, USA'],
['Florida Atlantic Univeristy, USA'],
['Florida Atlantic University, USA'],
['Florida International University, USA'],
['Florida State College at Jacksonville, USA'],
['Florida State Golf Association, USA'],
['Florida State University, USA'],
['Fontys  University of Applied Sciences, Netherlands'],
['Fontys Hogescholen, Netherlands'],
['Fontys University of Applied Sciences, Netherlands'],
['Fort Lewis College, USA'],
['Fort Wayne Community Schools, USA'],
['Framhaldssk?inn ?Mosfellsb? Israel'],
['Framingham State University, USA'],
['Frontenac Schools USD249, USA'],
['Furman University, USA'],
['Gallaudet University, USA'],
['Gardner-Webb University, USA'],
['Garinger High School, USA'],
['GC Hawley Middle School, USA'],
['George Brown College, Canada'],
['George Mason University, USA'],
['Georgia College, USA'],
['Georgia Institute of Technology, USA'],
['Georgia State University, USA'],
['Glendale Community College, USA'],
['Global Online Academy'],
['GLOBALFOUNDRIES, USA'],
['Goldenwest College, USA'],
['Goreville High School, USA'],
['Grand Valley State University, USA'],
['Grant MacEwan University, Canada'],
['Greensboro Day School, USA'],
['Grenoble Ecole de Management, France'],
['Griffin  Middle School, USA'],
['Griffin Middle School, USA'],
['Gujarat University, India'],
['Guru Gobind Singh Indraprastha University, India'],
['H.C.Ørsted Gymnasium, Denmark'],
['Haagse Hogeschool, Netherlands'],
['Hacettepe University, Turkey'],
['HAN University of Applied Sciences, Netherland'],
['HAN University of Applied Sciences, Netherlands'],
['Hanze University of Applied Science, Netherlands'],
['Harding University College of Pharmacy, USA'],
['Harper College, USA'],
['Harrisburg Area Community College, USA'],
['Harrow International School, Thailand'],
['Harvard University, South Korea'],
['Hebrew University, Jerusalem, Israel'],
['HEC Paris, France'],
['HEG Genève, Switzerland'],
['Hialeah Gardens High School, USA'],
['Higher Education Institutes'],
['Hillgrove High School, USA'],
['Hinsdale Central High School, USA'],
['Hiram College, USA'],
['HKU SPACE Community College, Hong Kong'],
['Hochschule Reutlingen, Germany'],
['Hofstra University, USA'],
['Hogeschool van Amsterdam, Netherland'],
['Hogeschool van Amsterdam, Netherlands'],
['Hogeschool, Netherlands'],
['Holy Cross of Davao College, Philippines'],
['Holyoke Community College, USA'],
['Home Learning College, UK'],
['Hoover City Schools, USA'],
['Hot Springs Intermediate School, USA'],
['Howard Payne University, USA'],
['Hudson County Community College, USA'],
['Hult Business School, Dubai, UAE'],
['Hult International Business School'],
['Hult International Business School, China'],
['Hult International Business School, UAE'],
['Hult International Business School, UK'],
['Hult International Business School, USA'],
['Hult International School of Business, USA'],
['Hurricane High School, USA'],
['Hwa Chong Institution, Singapore'],
['Hyde Leadership Charter School, USA'],
['IE Business School, Spain'],
['IESE Business School, Spain'],
['IESEG school of management, France'],
['IESEG School of management, France'],
['IESEG School of Management, France'],
['IESEG, France'],
['IFRJ, Brazil'],
['IIIT, Bangalore, India'],
['IIT Madras, India'],
['Illinois Institute of Technology, USA'],
['Illinois State University, USA'],
['IMC University of Applied Sciences Krems, Austria'],
['Imperial College London, UK'],
['IMT Dubai, UAE'],
['Indian Institute of Technology, Roorkee, India'],
['Indiana State University, USA'],
['Indiana University South Bend, USA'],
['Indiana University, USA'],
['Indonesia University of Education, Indonesia'],
['Inholland University of Applied Sciences, Netherland'],
['Instilla, Italy'],
['Institut Teknologi Bandung, Indonesia'],
['Institute for Tourism Studies, Macau'],
['Institute of Business Management, Pakistan'],
['Institute of Technical Education, Singapore'],
['International Community School, Singapore'],
['International School of Geneva, Switzerland'],
['International School of Zug and Luzern, Switzerland'],
['International Training Institute, Istanbul, Turkey'],
['Iowa State University, USA'],
['ISEN, France'],
['Isenberg Elementary, USA'],
['ITB School of Business and Management, Indonesia'],
['ITE, Singapore'],
['ITESM Campus Queretaro, Mexico'],
['ITESM, Mexico'],
['ITESM, Mexico'],
['ITESM, México'],
['ITESO, Mexico'],
['Ithaca College School of Music, USA'],
['Ithaca College, USA'],
['ITT Technical Institute, USA'],
['IU-PUI, USA'],
['Jacquelyn Humphrey, Australia'],
['James Cook University, Australia'],
['James Madison University, USA'],
['Jenae Leles Softball Academy, USA'],
['JN Fries Magnet School, USA'],
['John F Kennedy Middle School., USA'],
['Johnson'],
['Johnson &amp; Wales University, USA'],
['Kaj Munk College, Netherland'],
['Kansas State University, USA'],
['Kansas University Medical Center, USA'],
['Kaplan University'],
['Kean University, USA'],
['Kefato University of Trento, Italy'],
['Kendall College School of Education, USA'],
['Kennesaw State University, USA'],
['Kent State University, US'],
['Kent State University, USA'],
['Keshav Memorial Institute of Technology, India'],
['Kingsmead College, South Africa'],
['KIPP Ujima Village Academy, USA'],
['Knox High School, USA'],
['Koç University, Turkey'],
['Kolej PolyTech Mara, Malaysia'],
['Korea University Business School, South Korea'],
['KU Leuven, Belgium'],
['Kwantlen Polytechnic University, Canada'],
['La Salle University, Philippines'],
['Lakeridge Junior High, USA'],
['Lamar State College-Orange, USA'],
['Language Learning Center, USA'],
['Las Positas College, USA'],
['Lavalla Catholic College, Australia'],
['Lebanese American University, Lebanon'],
['Lee University, USA'],
['Leeds Trinity University, UK'],
['Lehman College, USA'],
['Liberty University, USA'],
['Lille 1 University, France'],
['Limestone College, USA'],
['Lincoln Memorial University, USA'],
['Little Skoolhouse'],
['London School of Economics, UK'],
['Los Alamitos High School Science, USA'],
['Louisiana State University, USA'],
['Lower Columbia College, USA'],
['LSE, UK'],
['MacEwan University, Canada'],
['Maharaja\'s College Ernakulam, India'],
['Manipal Academy of Banking, India'],
['MAQ Software'],
['Marwadi Education Foundation, India'],
['Matanzas High School, USA'],
['McMaster University, Canada'],
['MDSTAT Urgent Care, USA'],
['Medical Academy for Science &amp; Technolog, USA'],
['Medical College of Wisconsin, USA'],
['Medical University of the Americas'],
['Methodist Girls&#39; School, Singapore'],
['MGH Institute for Health Professions, USA'],
['Miami Dade College, USA'],
['Miami International University of Art and Design, USA'],
['Miami University of Ohio, USA'],
['Miami University, USA'],
['Michigan State University, Los Angeles, USA'],
['Michigan Technological University, USA'],
['Middlesex Community College, USA'],
['Middlesex University, UK'],
['Midway High School, USA'],
['Mikrocentrum, Netherlands'],
['Mill Chase Academy, UK'],
['Millennia Institute, Singapore'],
['Mills College,USA'],
['Milwaukee Area Technical College, USA'],
['MIO-ECSDE, Greece'],
['Miriam College High School, Philippines'],
['Missouri Southern State University, USA'],
['Missouri Valley College, USA'],
['MIT, USA'],
['Mohawk College, Canada'],
['Monash University'],
['Monash University, Australia'],
['Mondragon University, Spain'],
['Montclair State University, USA'],
['Monterey Peninsula College, USA'],
['Morningside College, USA'],
['Morton Ranch High School, USA'],
['Mount St. Mary\'s College, USA'],
['Mount Zion High School, USA'],
['Ms Susan Lee'],
['Mu Sigma'],
['Muhlenberg College, USA'],
['Multicultural Association of the Greater Moncton Area, Canada'],
['Myeongju Elementary School, South Korea'],
['MyPlanet Digital, Canada'],
['Myrtle Grove Middle School, USA'],
['N2N Services, USA'],
['Nabakrushna Choudhury Centre for Development Studies, India'],
['NAFA, Singapore'],
['Nanyang Junior College, Singapore'],
['Nanyang Technological University, Singapore'],
['Nash Rocky Mount Public Schools, USA'],
['National Central University, Taiwan'],
['National Research University, Russia'],
['National School of Computer Sciences, Tunisia'],
['National Taiwan Normal University, Taiwan'],
['National University of Ireland Galway , Ireland'],
['National University of Sciences and Technology, Pakistan'],
['National University of Singapore'],
['National University of Singapore , Singapore'],
['National University of Singapore, Singapore'],
['National University Singapore'],
['Navarro College, USA'],
['NC State University, USA'],
['New Fairfield High School, USA'],
['New Mexico State University, USA'],
['New Prairie United School Corporation, USA'],
['New Tech Odessa High School, USA'],
['New uni'],
['Newbury Park High School, USA'],
['Newcastle University, UK'],
['Newton Conover City Schools, USA'],
['Ngee Ann Polytechnic, Singapore'],
['NHTV University of Applied Sciences, Netherlands'],
['North Butler High School, USA'],
['North Carolina Central University, USA'],
['North Carolina State University, USA'],
['North Montgomery High School, USA'],
['North Park University , USA'],
['Northeastern University, USA'],
['Northern Arizona University, USA'],
['Northern Kentucky University, USA'],
['Northern MIchigan University, USA'],
['Northern Michigan University, USAniversity, USA'],
['Northern Nash High School, USA'],
['Northwestern Michigan College, USA'],
['Northwestern University, USA'],
['Northwood University, USA'],
['NRU Higher School of Economics, Russia'],
['NRU-Higher School of Economics, Russia'],
['NTNU, Norway'],
['NUI Galway, Ireland'],
['NUIG, Ireland'],
['Oakton Community College, USA'],
['Ogeechee Technical College, USA'],
['Ohio State University, USA'],
['Ohio University College of Business, USA'],
['Ohio UNiversity, USA'],
['Ohio University, USA'],
['Oklahoma State University Institute of Technology, USA'],
['Oklahoma State University, USA'],
['On-Ramps, USA'],
['Open-Quechua, Peru'],
['Oregon Institute of Technology, USA'],
['OSS World Challenge University'],
['Ostfalia University, Germany'],
['Otwell Middle School, USA'],
['Oulu School of Vocational Teacher Education, Finland'],
['Oxford College of Emory University, USA'],
['Pacific Lutheran University, USA'],
['Palm Beach Atlantic University, USA'],
['Palmer High School, USA'],
['Patrick County High School, USA'],
['Paxton Consolidated Schools, USA'],
['PBS Heemstede, Netherlands'],
['Pearl Academy, India'],
['Penn State University, USA'],
['Penn State World Campus, USA'],
['Pennsylvania State University, USA'],
['Peterson Schools, Mexico'],
['Petra Christian University, Indonesia'],
['Photography Studies College , Australia'],
['Pickens High School, USA'],
['Pima Community College, USA'],
['Polytechnic University of Hong Kong'],
['Pomona High School, USA'],
['Prairie View A&M University, USA'],
['PUC-PR, Brazil'],
['Punggol Green Primary School, Singapore'],
['Purdue North Central, USA'],
['Purdue University, USA'],
['Qatar University, Qatar'],
['Queen Elizabeth School, Hong Kong'],
['Queen&#39;s University, Canada'],
['Quinnipiac Univeirsty, USA'],
['Quinnipiac University, USA'],
['Radford University, USA'],
['Raffles College of Higher Education, Singapore'],
['Raffles Junior College, Singapore'],
['Red Deer College, Canada'],
['Regis University, USA'],
['Regius College Schagen, Netherlands'],
['Rensselaer Polytechnic Institute, USA'],
['Rice University, USA'],
['Riley High School, USA'],
['Riverwood International Charter School, USA'],
['RMIT University, Australia'],
['Robert Gordon University, UK'],
['ROC van Amsterdam, Netherlands'],
['Rochester Institute of Technology, USA'],
['Rockdale High School, USA'],
['RoCvA, Netherlands'],
['Rocva, Netherlands'],
['Rotterdam University of Applied Science, Netherlands'],
['Rowan College at Gloucester County, USA'],
['Rowan University, USA'],
['Royal St. George&#39;s College, Canada'],
['Roz Hussin, USA'],
['Rutgers University, USA'],
['S P Jain School of Global Management'],
['Saint Francis University, USA'],
['Saint John\'s Catholic School, Indonesia'],
['Saint Louis University, USA'],
['Saint Mary\'s College of California, USA'],
['SAIT Polytechnic, Canada'],
['Salem State University, USA'],
['Saline High School, USA'],
['Samford University, USA'],
['San Diego County Office of Education, USA'],
['San Jose State University, USA'],
['Santa Clara University, USA'],
['Santa Fe College, USA'],
['Santa María del Pilar, Spain'],
['Saxion University, Netherlands'],
['Saxion, Netherlands'],
['SC Nova Gorica, Slovenia'],
['Scott Community College, USA'],
['SECAmb TtP, UK'],
['Sekolah Menengah Kebangsaan Bukit Jalor, Malaysia'],
['Sekolah Menengah Sayyidina Ali, Brunei Darussalam'],
['Seneca College, Canada'],
['Sengkang Secondary School, Singapore'],
['Shairf University of Technology, Iran'],
['Shanghai University of Int. Business and Economics, China'],
['SHATEC Pte Ltd, Singapore'],
['Sheridan College, Canada'],
['Showa Women&#39;s University, Japan'],
['Silicon Straits, Singapore'],
['Simmons College, USA'],
['Simon Fraser University, Canada'],
['Singapore Chinese Girls\' School'],
['Singapore Institute of Technology'],
['Singapore Institute of Technology, Singapore'],
['Singapore Management University, Singapore'],
['Singapore Polytechnic'],
['Singapore Polytechnic, Singapore'],
['Singapore Polytechnic, Singapore'],
['Sint Lievens College, Belgium'],
['Sint Pieters College, Belgium'],
['Sint-Lievens College, Belgium'],
['Sint-Lodewijk Campus Van Celst, Belgium'],
['South Christian High School, USA'],
['South San Francisco High School, USA'],
['Southeast Missouri State University, USA'],
['Southern Alberta Institute of Technology, Canada'],
['Southern California University of Health Sciences, USA'],
['Southern College of Optometry, USA'],
['Southern Methodist University, USA'],
['Southwest Tech, USA'],
['Southwestern Law School, USA'],
['Southworks, Argentina'],
['Spelman College, USA'],
['Spire, Kenya'],
['Spring Hill College, USA'],
['St Catherine&#39;s Catholic College, Australia'],
['St Ives High School, Australia'],
['St Mark&#39;s School, USA'],
['St. Anne Grade School, USA'],
['St. David Catholic Elementary, Canada'],
['St. Lawrence College, Canada'],
['St. Mark\'s School, USA'],
['St. Olaf College, USA'],
['St. Scholastica&#39;s College, Australia'],
['St. Vincent Pallotti High School, USA'],
['Star of the Sea Catholic College, Australia'],
['State University of New York at Brockport, USA'],
['stayzilla.com, India'],
['Stellenbosch University, South Africa'],
['STEM Launch, USA'],
['Stephen F. Austin State University, USA'],
['Stevens Institute of Technology, USA'],
['Sun Valley High School, CA, USA'],
['SUNY Jefferson Community College, USA'],
['SUNY Korea, Republic of Korea'],
['SUNY, Korea'],
['SUTD, Singapore'],
['Swinburne Online, Australia'],
['Swinburne University of Technology, Australia'],
['Swinburne University, Australia'],
['Tabor Adelaide, Australia'],
['Taoyuan Ping-Jen Senior High School, Taiwan'],
['Tarleton State University, USA'],
['Tarrant County College, USA'],
['Tarumanagara University, Indonesia'],
['Tec de Monterrey, Mexico'],
['Tech Mahindra, India'],
['Technical University of Denmark, Denmark'],
['Tecnol?ico de Monterrey Campus Puebla, Mexico'],
['Tecnologico de Monterrey, Mexico'],
['Teesside University, UK'],
['Temasek Polytechnic, Singapore'],
['Temple University, USA'],
['Test University'],
['Texas A'],
['Texas A&amp;M Health Science Center, USA'],
['Texas A&amp;M International University, USA'],
['Texas A&amp;M University, USA'],
['Texas Lutheran University, USA'],
['Texas Southern University, USA'],
['Texas Tech University, USA'],
['Texas Woman&#39;s University, USA'],
['The Hague University of Applied Sciences, Netherlands'],
['The Hong Kong Polytechnic University, Hong Kong'],
['The Kibbutzim College of Education, Israel'],
['The King&#39;s University, Canada'],
['The Market Weighton School, UK'],
['The Master&#39;s School, USA'],
['The Petroleum Institute, UAE'],
['The Shipping Academy, Singapore'],
['The Univeersity of Texas at Austin, USA'],
['The University of Akron, USA'],
['The University of Auckland, New Zealand'],
['The University of Kansas Medical Center, USA'],
['The University of Manchester, UK'],
['The University of Melbourne'],
['The University of North Carolina at Greensboro, USA'],
['The University of Texas at Arlington, USA'],
['The University of Texas at Austin, USA'],
['The University of Texas at El Paso, USA'],
['The University of Western Australia'],
['The University of Wisconsin - Madison, USA'],
['Thiel College , USA'],
['Thiel College, USA'],
['Thomas Nelson Community College, USA'],
['Tianfu University Chengdu China, China'],
['TIAS Business School, Netherlands'],
['Toledo Prudente Centro Universitário, Brazil'],
['Trakia University, Bulgaria'],
['Transylvania County Schools, USA'],
['Tribeca Flashpoint Academy, USA'],
['Trinity Western University, Canada'],
['TU Delft, Netherlands'],
['TU Dresden, Germany'],
['Tufts University, USA'],
['Tunku Abdul Rahman University, Malaysia'],
['UC San Diego, USA'],
['UCSI University, Malaysia'],
['UFRN, Brazil'],
['UJAK, Czech Republic'],
['Union Mine High School, USA'],
['Unitec Institute of Technology, New Zealand'],
['Univeristy of North Georgia, USA'],
['Universidad Autónoma de Baja California, Mexico'],
['Universidad Catolica Andres Bello, Venezuela'],
['Universidad Católica Andrés Bello, Venezuela'],
['Universidad Complutense de Madrid, Spain'],
['Universidad Complutense, Spain'],
['Universidad de Chile'],
['Universidad De Chile, Chile'],
['Universidad de Ingeniería y Tecnología, Peru'],
['Universidad de Los Andes, Colombia'],
['Universidad de Navarra, Spain'],
['Universidad del Este, Puerto Rico'],
['Universidad del Pa? Vasco, Spain'],
['Universidad El Bosque, Colombia'],
['Universidad Nacional de San Agustin, Peru'],
['Universidad Nacional de San Agustín, Peru'],
['Universidad ORT Uruguay , Uruguay'],
['Universidad ORT Uruguay, Uruguay'],
['Universidad Politecnica de Madrid, Spain'],
['Universidad Pública de Navarra, Spain'],
['Universidade Catolica de Brasilia, Brazil'],
['Universidade Católica de Brasília, Brazil'],
['Universidade de São Paulo, Brazil'],
['Universidade do Minho, Portugal'],
['Università Cattolica - Milano, Italy'],
['Universitas Pelita Harapan, Indonesia'],
['Universität Augsburg, Germany'],
['Universitat Autonoma de Barcelona, Spain'],
['Universität der Bundeswehr München, Germany'],
['Universite Laval, Canada'],
['Universiteit Gent, Belgium'],
['Universiti Kebangsaan Malaysia, Malaysia'],
['Universiti Malaysia Sarawak, Malaysia'],
['Universiti Putra Malaysia, Malaysia'],
['Universiti Teknologi Malaysia, Malaysia'],
['University at Buffalo, USA'],
['University College Dublin, Ireland'],
['University College Leuven-Limburg, Belgium'],
['University College London'],
['University College London, UK'],
['University College of Technology Sarawak, Malaysia'],
['University College Sjaelland, Denmark'],
['University Kuala Lumpur, Malaysia'],
['University of Adelaide, Australia'],
['University of Akron, USA'],
['University of Alabama at Birmingham, USA'],
['University of Alabama Birmingham, USA'],
['University of Alaska Anchorage, USA'],
['University of Alaska, USA'],
['University of Alberta, Canada'],
['University of Antwerp, Belgium'],
['University of Arizona, USA'],
['University of Aruba, Aruba'],
['University of Auckland, New Zealand'],
['University of Bath, UK'],
['University of Bradford, UK'],
['University of Bristol, UK'],
['University of British Columbia, Canada'],
['University of California Davis, USA'],
['University of California, Berkeley, USA'],
['University of California, Los Angeles, USA'],
['University of California, USA'],
['University of Central Florida, USA'],
['University of Central Lancashire, UK'],
['University of Central Oklaoma, USA'],
['University of Chichester, UK'],
['University of Cincinnati, USA'],
['University of Colorado at Boulder, USA'],
['University of Colorado at Colorado Springs, USA'],
['University of Colorado Boulder, USA'],
['University of Colorado Colorado Springs, USA'],
['University of Colorado, USA'],
['University of Dallas, USA'],
['University of Delaware, USA'],
['University of Denver, USA'],
['University of Florida , USA'],
['University of Florida, USA'],
['University of Geneva, Switzerland'],
['University of Georgia, USA'],
['University of Hertfordshire, UK'],
['University of Hong Kong'],
['University of Houston, USA'],
['University of Huddersfield, UK'],
['University of Idaho, USA'],
['University of Illinois at Chicago, USA'],
['University of Illinois at Urbana Champaign, USA'],
['University of Illinois at Urbana-Champaign, USA'],
['University of Illinois, USA'],
['University of Indianapolis, USA'],
['University of Inholland, Netherlands'],
['University of Iowa, USA'],
['University of Kansas Medical Center, USA'],
['University of Kansas, USA'],
['University of Kentucky, USA'],
['University of Limerick, Ireland'],
['University of Louisiana Monroe, USA'],
['University of Louisville, USA'],
['University of Maine, USA'],
['University of Manchester, UK'],
['University of Manila, Philippines'],
['University of Maryland Baltimore County, USA'],
['University of Maryland University College, USA'],
['University of Maryland, Baltimore County, USA'],
['University of Maryland, USA'],
['University of Massachusetts Boston, USA'],
['University of Massachusetts, USA'],
['University of Memphis, USA'],
['University of Michigan, USA'],
['University of Minnesota, USA'],
['University of Mississippi, USA'],
['University of Missouri, USA'],
['University of Nebraska Lincoln, USA'],
['University of Nebraska-Lincoln, USA'],
['University of Nebraska, Lincoln, USA'],
['University of Nebraska, USA'],
['University of Nevada, USA'],
['University of New Brunswick, Canada'],
['University of New South Wales, Australia'],
['University of North Carolina at Greensboro, USA'],
['University of North Carolina Greensboro, USA'],
['University of North Carolina, USA'],
['University of North Florida, USA'],
['University of North Texas, USA'],
['University of Northampton, UK'],
['University of Northern Colorado, USA'],
['University of Notre Dame, USA'],
['University of Nottingham Malaysia Campus, Malaysia'],
['University of Oklahoma, USA'],
['University of Ottawa, Canada'],
['University of Paderborn, Germany'],
['University of PIttsburgh, USA'],
['University of Pittsburgh, USA'],
['University of Portsmouth, UK'],
['University of Pretoria, South Africa'],
['University of Queensland, Australia'],
['University of Rhode Island, USA'],
['University of Saint Francis, USA'],
['University of Saint Mary, USA'],
['University of Salford, UK'],
['University of San Diego, USA'],
['University of Saskatchewan, Canada'],
['University of Scranton, USA'],
['University of South Australia, Australia'],
['University of South Carolina Aiken, USA'],
['University of South Florida, USA'],
['University of Southampton, UK'],
['University of Southern California, USA'],
['University of Southern Maine, USA'],
['University of St Andrews, Scotland'],
['University of St Andrews, UK'],
['University of St. Thomas, USA'],
['University of Sydney, Australia'],
['University of Tasmania, Australia'],
['University of Tennessee Knoxville, USA'],
['University of Tennessee, Knoxville, USA'],
['University of Tennessee, USA'],
['University of Texas - Austin, USA'],
['University of Texas Arlington, USA'],
['University of Texas at Arlington, USA'],
['University of Texas at Austin, USA'],
['University of Texas at San Antonio, USA'],
['University of Texas Health Science Center San Antonio, USA'],
['University of Texas Rio Grande Valley, USA'],
['University of Texas, Austin, USA'],
['University of Texas, El Paso, USA'],
['University of the Basque Country, Spain'],
['University of the Cordilleras, Philippines'],
['University of the Faroe Islands, Faroe Islands'],
['University of the Pacific, USA'],
['University of the Philippines'],
['University of the Western Cape, South Africa'],
['University of Toledo, USA'],
['University of Toronto, Canada'],
['University of Trento, Italy'],
['University of Twente, Netherlands'],
['University of Virginia, USA'],
['University of Waikato, New Zealand'],
['University of Washington, USA'],
['University of Waterloo, Canada'],
['University of Western Australia'],
['University of Western Sydney, Australia'],
['University of Wisconsin Oshkosh, USA'],
['University of Wisconsin School of Business, USA'],
['University of Wisconsin-Madison, USA'],
['University of Wisconsin-Platteville, USA'],
['University of Wisconsin, Green Bay, USA'],
['University of Wisconsin, Stevens Point, USA'],
['University of Wisconsin, USA'],
['University Utrecht, Netherlands'],
['Univerza v Ljubljani, Slovenia'],
['Univesity of the Cordilleras, Philippines'],
['Unknown Institute'],
['Unversity of San Diego, USA'],
['UOIT, Canada'],
['Urbandale High School, USA'],
['US Army'],
['US Army Engineer School, USA'],
['US Army Warrant Officer Advanced Course, USA'],
['UT Tyler, USA'],
['Utah Valley University, USA'],
['Utrecht University, Netherlands'],
['Utrecht University, Netherlands'],
['Valparaiso University, USA'],
['Vammalan lukio, Finland'],
['VATSIM, UK'],
['Viatienen SWeTe, Belgium'],
['Viral Academy'],
['Virginia Commonwealth University, USA'],
['Virginia State University, USA'],
['VIT University Vellore, India'],
['Vrije Universiteit Brussel, Belgium'],
['VU University, Netherland'],
['Walnut Hills High School, USA'],
['Warrensburg High School, USA'],
['Washington and Lee University, USA'],
['Washington State University, USA'],
['Washington University in Saint Louis, USA'],
['Washington University, USA'],
['Waubun-Ogema-White Earth Community Schools, USA'],
['Weber State University, USA'],
['Webster University, USA'],
['Wells College, USA'],
['Wescale, Germany'],
['West Boca Raton High School, USA'],
['West Virginia Department of Education, USA'],
['West Virginia University, USA'],
['Western Carolina University, USA'],
['Western Illinois University, USA'],
['Western Kentucky University, USA'],
['Western Technical College, USA'],
['Western University, Canada'],
['Western Washington University, USA'],
['Westminster Seafarer Management Philippines Inc.'],
['Wheatland Center School, USA'],
['White House Heritage High School, USA'],
['Will Rogers Junior High, USA'],
['William A Hough High School, USA'],
['Wilmington University, USA'],
['Windesheim Honours College, Netherlands'],
['Woodbury University, USA'],
['Worcester Polytechnic Institute, USA'],
['Wright State University, USA'],
['WSU Vancouver, USA'],
['Xavier School, Philippines'],
['Xavier University of Louisiana, USA'],
['Yale University, USA'],
['Yale-NUS, Singapore'],
['Yasar University, Turkey'],
['Yeejin Jang'],
['York College, USA'],
['York University, Canada'],
['Young harris College, USA'],
['YTI Career Institute, USA'],
['Zane State College, USA']
];
