name: Comment when an issue is labelled

on:
  issues:
    types:
      - labeled

jobs:
  comment:
    if: github.event.label.name == 'good first issue' || github.event.label.name == 'help wanted'
    permissions:
      contents: read
      issues: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          sparse-checkout: .github/scripts/comment-issue-label.js
          sparse-checkout-cone-mode: false
      - name: Add comment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const script = require('./.github/scripts/comment-issue-label.js');
            await script({ github, context, core });
